<?php

return [
    'languages' => [
        ["code" => "CHN", "name" => "Chinese (Simplified)"],
        ["code" => "YUH", "name" => "Chinese (Traditional)"],
        ["code" => "CZC", "name" => "Czech"],
        ["code" => "DAN", "name" => "Danish"],
        ["code" => "NLD", "name" => "Dutch"],
        ["code" => "ENG", "name" => "English"],
        ["code" => "FIN", "name" => "Finnish"],
        ["code" => "FRN", "name" => "French"],
        ["code" => "GER", "name" => "German"],
        ["code" => "GRK", "name" => "Greek"],
        ["code" => "HND", "name" => "Hindi"],
        ["code" => "HUN", "name" => "Hungarian"],
        ["code" => "IND", "name" => "Indonesian"],
        ["code" => "ITA", "name" => "Italian"],
        ["code" => "JPN", "name" => "Japanese"],
        ["code" => "KOR", "name" => "Korean"],
        ["code" => "ZLM", "name" => "Malay"],
        ["code" => "NOR", "name" => "Norwegian"],
        ["code" => "POL", "name" => "Polish"],
        ["code" => "POR", "name" => "Portuguese"],
        ["code" => "RON", "name" => "Romanian"],
        ["code" => "RUS", "name" => "Russian"],
        ["code" => "SPN", "name" => "Spanish"],
        ["code" => "SWE", "name" => "Swedish"],
        ["code" => "THA", "name" => "Thai"],
        ["code" => "TRK", "name" => "Turkish"],
        ["code" => "UKR", "name" => "Ukrainian"],
        ["code" => "VIE", "name" => "Vietnamese"],
    ],
    'bible_languages' => [
        'Danish',
        'German',
        'Italian',
        'Korean',
        'Norwegian',
        'Polish',
        'Thai',
    ],
    'religions' => [
        ["id" => 1, "name" => "Anglican"],
        ["id" => 2, "name" => "Baptist"],
        ["id" => 3, "name" => "Calvinist"],
        ["id" => 4, "name" => "Catholic"],
        ["id" => 5, "name" => "Eastern Orthodox"],
        ["id" => 6, "name" => "Jehovah’s Witness"],
        ["id" => 7, "name" => "Latter-day Saints"],
        ["id" => 8, "name" => "Lutheran"],
        ["id" => 9, "name" => "Methodist"],
        ["id" => 10, "name" => "Nondenominational"],
        ["id" => 11, "name" => "Oriental Orthodox"],
        ["id" => 12, "name" => "Pentecostal"],
        ["id" => 13, "name" => "Presbyterian"],
        ["id" => 14, "name" => "Quaker"],
        ["id" => 15, "name" => "Restorationist"],
    ]
];
